---
grails:
    profile: web-plugin
    codegen:
        defaultPackage: grails.plugins.ignite
    gorm:
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false

# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    jmx:
        enabled: true

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
endpoints:
    jmx:
        unique-names: true

---
dataSource:
    pooled: true
    jmxExport: true
    driverClassName: "org.h2.Driver"
    username: "sa"
    password: ""

hibernate:
    cache.use_second_level_cache: true
    cache.use_query_cache: false
    #cache.region.factory_class: 'net.sf.ehcache.hibernate.EhCacheRegionFactory' # Hibernate 3
    #cache.region.factory_class: 'org.hibernate.cache.ehcache.EhCacheRegionFactory' # Hibernate 4
    #singleSession: true # configure OSIV singleSession mode

    cache.region.factory_class: 'grails.plugins.ignite.HibernateRegionFactory'
    org.apache.ignite.hibernate.ignite_instance_name: 'grid'
    org.apache.ignite.hibernate.default_access_type: 'READ_ONLY' # see Ignite docs

    generate_statistics: true
    use_structured_entries: true

environments:
    development:
        dataSource:
            dbCreate: create-drop # one of 'create', 'create-drop', 'update', 'validate', ''
            url: "jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE"

    test:
        dataSource:
            dbCreate: update
            url: "jdbc:h2:mem:testDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_DELAY=-1"
        ignite:
            enabled: true
            gridName: grid
            config.locations:
            - file:ignite/conf/IgniteResources.groovy
            - file:ignite/conf/IgniteCacheResources.groovy
            l2CacheEnabled: true
            discoverySpi.multicastDiscovery: true
            peerClassLoadingEnabled: true

    production:
        dataSource:
            dbCreate: update
            url: "jdbc:h2:prodDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE"
            properties:
                # See http://grails.org/doc/latest/guide/conf.html#dataSource for documentation
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 10 * 60000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
